/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using Org.OpenAPITools.Attributes;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpDelete]
        [Route("/ifcx-api/layers/{layerId}")]
        [ValidateModelState]
        [SwaggerOperation("LayerRoutesDeleteLayer")]
        public virtual IActionResult LayerRoutesDeleteLayer([FromRoute (Name = "layerId")][Required]string layerId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers/{layerId}")]
        [ValidateModelState]
        [SwaggerOperation("LayerRoutesGetLayer")]
        [SwaggerResponse(statusCode: 200, type: typeof(LayerDetails), description: "The request has succeeded.")]
        public virtual IActionResult LayerRoutesGetLayer([FromRoute (Name = "layerId")][Required]string layerId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            exampleJson = "{\r\n  \"latestVersion\" : \"latestVersion\",\r\n  \"id\" : \"id\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<LayerDetails>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers/{layerId}/history")]
        [ValidateModelState]
        [SwaggerOperation("LayerRoutesGetLayerHistory")]
        [SwaggerResponse(statusCode: 200, type: typeof(LayerHistory), description: "The request has succeeded.")]
        public virtual IActionResult LayerRoutesGetLayerHistory([FromRoute (Name = "layerId")][Required]string layerId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            exampleJson = "{\r\n  \"versions\" : [ \"versions\", \"versions\" ],\r\n  \"id\" : \"id\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<LayerHistory>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="layerRoutesUpdateLayerRequest"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPut]
        [Route("/ifcx-api/layers/{layerId}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("LayerRoutesUpdateLayer")]
        public virtual IActionResult LayerRoutesUpdateLayer([FromRoute (Name = "layerId")][Required]string layerId, [FromBody]LayerRoutesUpdateLayerRequest layerRoutesUpdateLayerRequest)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPost]
        [Route("/ifcx-api/layers/{layerId}/upload-ifcx-blob-url")]
        [ValidateModelState]
        [SwaggerOperation("LayerRoutesUploadIfcxBlobUrl")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "The request has succeeded.")]
        public virtual IActionResult LayerRoutesUploadIfcxBlobUrl([FromRoute (Name = "layerId")][Required]string layerId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<string>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="versionId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers/{layerId}/versions/{versionId}")]
        [ValidateModelState]
        [SwaggerOperation("LayerVersionRoutesGetLayerVersion")]
        [SwaggerResponse(statusCode: 200, type: typeof(LayerVersion), description: "The request has succeeded.")]
        public virtual IActionResult LayerVersionRoutesGetLayerVersion([FromRoute (Name = "layerId")][Required]string layerId, [FromRoute (Name = "versionId")][Required]string versionId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            exampleJson = "{\r\n  \"previousVersionId\" : \"previousVersionId\",\r\n  \"versionId\" : \"versionId\",\r\n  \"layerId\" : \"layerId\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<LayerVersion>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="versionId"></param>
        /// <param name="downloadType"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPut]
        [Route("/ifcx-api/layers/{layerId}/versions/{versionId}/download-ifcx")]
        [ValidateModelState]
        [SwaggerOperation("LayerVersionRoutesLayerIfcx")]
        [SwaggerResponse(statusCode: 200, type: typeof(LayerVersionIfcxFile), description: "The request has succeeded.")]
        public virtual IActionResult LayerVersionRoutesLayerIfcx([FromRoute (Name = "layerId")][Required]string layerId, [FromRoute (Name = "versionId")][Required]string versionId, [FromQuery (Name = "downloadType")][Required()]IfcxFileDownloadType downloadType)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            exampleJson = "{\r\n  \"blobUrl\" : \"blobUrl\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<LayerVersionIfcxFile>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="versionId"></param>
        /// <param name="path"></param>
        /// <param name="provenance"></param>
        /// <param name="expandChildren"></param>
        /// <param name="expandChildrenRecursive"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers/{layerId}/versions/{versionId}/query")]
        [ValidateModelState]
        [SwaggerOperation("LayerVersionRoutesQuery")]
        public virtual IActionResult LayerVersionRoutesQuery([FromRoute (Name = "layerId")][Required]string layerId, [FromRoute (Name = "versionId")][Required]string versionId, [FromQuery (Name = "path")][Required()]string path, [FromQuery (Name = "provenance")][Required()]bool provenance, [FromQuery (Name = "expandChildren")][Required()]bool expandChildren, [FromQuery (Name = "expandChildrenRecursive")][Required()]bool expandChildrenRecursive)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layersCreateLayerRequest"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPost]
        [Route("/ifcx-api/layers")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("LayersCreateLayer")]
        public virtual IActionResult LayersCreateLayer([FromBody]LayersCreateLayerRequest layersCreateLayerRequest)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers")]
        [ValidateModelState]
        [SwaggerOperation("LayersLayers")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<LayerStatus>), description: "The request has succeeded.")]
        public virtual IActionResult LayersLayers()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            string exampleJson = null;
            exampleJson = "[ {\r\n  \"latestVersion\" : \"latestVersion\",\r\n  \"id\" : \"id\"\r\n}, {\r\n  \"latestVersion\" : \"latestVersion\",\r\n  \"id\" : \"id\"\r\n} ]";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<LayerStatus>>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="versionsRoutesCreateLayerVersionRequest"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPost]
        [Route("/ifcx-api/layers/{layerId}/versions")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("VersionsRoutesCreateLayerVersion")]
        public virtual IActionResult VersionsRoutesCreateLayerVersion([FromRoute (Name = "layerId")][Required]string layerId, [FromBody]VersionsRoutesCreateLayerVersionRequest versionsRoutesCreateLayerVersionRequest)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }
    }
}
