/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using IfcxApi.Server.Converters;

namespace IfcxApi.Server.Models
{ 
        /// <summary>
        /// Gets or Sets CreateLayerVersionResponseState
        /// </summary>
        
        public enum CreateLayerVersionResponseState
        {
            
            /// <summary>
            /// Enum OK for OK
            /// </summary>
            [EnumMember(Value = "OK")]
            OK = 1,
            
            /// <summary>
            /// Enum OUTOFDATE for OUT_OF_DATE
            /// </summary>
            [EnumMember(Value = "OUT_OF_DATE")]
            OUTOFDATE = 2
        }
}
