/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using IfcxApi.Server.Converters;

namespace IfcxApi.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CreateLayerVersionCommand : IEquatable<CreateLayerVersionCommand>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets PreviousLayerVersionId
        /// </summary>
        [Required]
        [DataMember(Name="previousLayerVersionId", EmitDefaultValue=true)]
        public Guid PreviousLayerVersionId { get; set; }

        /// <summary>
        /// Gets or Sets BlobId
        /// </summary>
        [Required]
        [DataMember(Name="blobId", EmitDefaultValue=true)]
        public Guid BlobId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateLayerVersionCommand {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PreviousLayerVersionId: ").Append(PreviousLayerVersionId).Append("\n");
            sb.Append("  BlobId: ").Append(BlobId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CreateLayerVersionCommand)obj);
        }

        /// <summary>
        /// Returns true if CreateLayerVersionCommand instances are equal
        /// </summary>
        /// <param name="other">Instance of CreateLayerVersionCommand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateLayerVersionCommand other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    PreviousLayerVersionId == other.PreviousLayerVersionId ||
                    
                    PreviousLayerVersionId.Equals(other.PreviousLayerVersionId)
                ) && 
                (
                    BlobId == other.BlobId ||
                    
                    BlobId.Equals(other.BlobId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    
                    hashCode = hashCode * 59 + PreviousLayerVersionId.GetHashCode();
                    
                    hashCode = hashCode * 59 + BlobId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CreateLayerVersionCommand left, CreateLayerVersionCommand right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CreateLayerVersionCommand left, CreateLayerVersionCommand right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
