/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using IfcxApi.Server.Converters;

namespace IfcxApi.Server.Models
{ 
        /// <summary>
        /// Gets or Sets IfcxFileDownloadType
        /// </summary>
        
        public enum IfcxFileDownloadType
        {
            
            /// <summary>
            /// Enum JustThisVersionEnum for just_this_version
            /// </summary>
            [EnumMember(Value = "just_this_version")]
            JustThisVersionEnum = 1,
            
            /// <summary>
            /// Enum WholeLayerHistoryIntactEnum for whole_layer_history_intact
            /// </summary>
            [EnumMember(Value = "whole_layer_history_intact")]
            WholeLayerHistoryIntactEnum = 2,
            
            /// <summary>
            /// Enum WholeLayerHistoryCondensedEnum for whole_layer_history_condensed
            /// </summary>
            [EnumMember(Value = "whole_layer_history_condensed")]
            WholeLayerHistoryCondensedEnum = 3,
            
            /// <summary>
            /// Enum WholeLayerAndImportsHistoryCondensedEnum for whole_layer_and_imports_history_condensed
            /// </summary>
            [EnumMember(Value = "whole_layer_and_imports_history_condensed")]
            WholeLayerAndImportsHistoryCondensedEnum = 4
        }
}
