// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var ifcIndexFile = IfcIndexFile.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class IfcIndexFile
    {
        [JsonPropertyName("attributeTables")]
        public AttributeTableElement[] AttributeTables { get; set; }

        [JsonPropertyName("header")]
        public IfcIndexFileHeader Header { get; set; }

        [JsonPropertyName("imports")]
        public ImportElement[] Imports { get; set; }

        [JsonPropertyName("sections")]
        public SectionElement[] Sections { get; set; }
    }

    public partial class AttributeTableElement
    {
        [JsonPropertyName("filename")]
        public string Filename { get; set; }

        [JsonPropertyName("schema")]
        public object Schema { get; set; }

        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }
    }

    public partial class IfcIndexFileHeader
    {
        [JsonPropertyName("ifcxVersion")]
        public string IfcxVersion { get; set; }
    }

    public partial class ImportElement
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("integrity")]
        public string Integrity { get; set; }

        [JsonPropertyName("uri")]
        public string Uri { get; set; }
    }

    public partial class SectionElement
    {
        [JsonPropertyName("header")]
        public SectionHeader Header { get; set; }

        [JsonPropertyName("nodes")]
        public NodeElement[] Nodes { get; set; }
    }

    public partial class SectionHeader
    {
        [JsonPropertyName("author")]
        public string Author { get; set; }

        [JsonPropertyName("dataVersion")]
        public string DataVersion { get; set; }

        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("timestamp")]
        public string Timestamp { get; set; }
    }

    public partial class NodeElement
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("attributes")]
        public AttributeElement[] Attributes { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("children")]
        public ChildElement[] Children { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("inherits")]
        public ChildElement[] Inherits { get; set; }

        [JsonPropertyName("path")]
        public string Path { get; set; }
    }

    public partial class AttributeElement
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("opinion")]
        public Opinion Opinion { get; set; }

        [JsonPropertyName("value")]
        public Value Value { get; set; }
    }

    public partial class Value
    {
        [JsonPropertyName("componentIndex")]
        public long ComponentIndex { get; set; }

        [JsonPropertyName("fileIndex")]
        public long FileIndex { get; set; }
    }

    public partial class ChildElement
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("opinion")]
        public Opinion Opinion { get; set; }

        [JsonPropertyName("value")]
        public string Value { get; set; }
    }

    public enum TypeEnum { Ndjson, Parquet };

    public enum Opinion { Delete, PassThrough, Value };

    public partial class IfcIndexFile
    {
        public static IfcIndexFile FromJson(string json) => JsonSerializer.Deserialize<IfcIndexFile>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this IfcIndexFile self) => JsonSerializer.Serialize(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                TypeEnumConverter.Singleton,
                OpinionConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class TypeEnumConverter : JsonConverter<TypeEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum);

        public override TypeEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "NDJSON":
                    return TypeEnum.Ndjson;
                case "PARQUET":
                    return TypeEnum.Parquet;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void Write(Utf8JsonWriter writer, TypeEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case TypeEnum.Ndjson:
                    JsonSerializer.Serialize(writer, "NDJSON", options);
                    return;
                case TypeEnum.Parquet:
                    JsonSerializer.Serialize(writer, "PARQUET", options);
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }

    internal class OpinionConverter : JsonConverter<Opinion>
    {
        public override bool CanConvert(Type t) => t == typeof(Opinion);

        public override Opinion Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "DELETE":
                    return Opinion.Delete;
                case "PASS_THROUGH":
                    return Opinion.PassThrough;
                case "VALUE":
                    return Opinion.Value;
            }
            throw new Exception("Cannot unmarshal type Opinion");
        }

        public override void Write(Utf8JsonWriter writer, Opinion value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case Opinion.Delete:
                    JsonSerializer.Serialize(writer, "DELETE", options);
                    return;
                case Opinion.PassThrough:
                    JsonSerializer.Serialize(writer, "PASS_THROUGH", options);
                    return;
                case Opinion.Value:
                    JsonSerializer.Serialize(writer, "VALUE", options);
                    return;
            }
            throw new Exception("Cannot marshal type Opinion");
        }

        public static readonly OpinionConverter Singleton = new OpinionConverter();
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
