/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLayerVersionIfcxFileFromDiscriminatorValue, IfcxFileDownloadType, type LayerVersionIfcxFile } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/layers/{layerId}/versions/{versionId}/download-ifcx
 */
export interface DownloadIfcxRequestBuilder extends BaseRequestBuilder<DownloadIfcxRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LayerVersionIfcxFile>}
     */
     put(requestConfiguration?: RequestConfiguration<DownloadIfcxRequestBuilderPutQueryParameters> | undefined) : Promise<LayerVersionIfcxFile | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(requestConfiguration?: RequestConfiguration<DownloadIfcxRequestBuilderPutQueryParameters> | undefined) : RequestInformation;
}
export interface DownloadIfcxRequestBuilderPutQueryParameters {
    downloadType?: IfcxFileDownloadType;
}
/**
 * Uri template for the request builder.
 */
export const DownloadIfcxRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers/{layerId}/versions/{versionId}/download-ifcx?downloadType={downloadType}";
/**
 * Metadata for all the requests in the request builder.
 */
export const DownloadIfcxRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: DownloadIfcxRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createLayerVersionIfcxFileFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
