/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBlobResponseFromDiscriminatorValue, type BlobResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/layers/{layerId}/upload-ifcx-blob-url
 */
export interface UploadIfcxBlobUrlRequestBuilder extends BaseRequestBuilder<UploadIfcxBlobUrlRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BlobResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BlobResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UploadIfcxBlobUrlRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers/{layerId}/upload-ifcx-blob-url";
/**
 * Metadata for all the requests in the request builder.
 */
export const UploadIfcxBlobUrlRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UploadIfcxBlobUrlRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createBlobResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
