// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.IfcxApi.Download.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.IfcxApi.Download
{
    /// <summary>
    /// Builds and executes requests for operations under \ifcx-api\download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ApiSdk.ifcxApi.download.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ApiSdk.IfcxApi.Download.Item.WithBlobItemRequestBuilder"/></returns>
        public global::ApiSdk.IfcxApi.Download.Item.WithBlobItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("blobId", position);
                return new global::ApiSdk.IfcxApi.Download.Item.WithBlobItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ApiSdk.ifcxApi.download.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ApiSdk.IfcxApi.Download.Item.WithBlobItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ApiSdk.IfcxApi.Download.Item.WithBlobItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("blobId", position);
                return new global::ApiSdk.IfcxApi.Download.Item.WithBlobItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.IfcxApi.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ifcx-api/download", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.IfcxApi.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ifcx-api/download", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
