/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreateLayerVersionCommandFromDiscriminatorValue, serializeCreateLayerVersionCommand, type CreateLayerVersionCommand } from '../../../../models/index.js';
// @ts-ignore
import { type WithVersionItemRequestBuilder, WithVersionItemRequestBuilderNavigationMetadata, WithVersionItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {VersionsPostRequestBody}
 */
// @ts-ignore
export function createVersionsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoVersionsPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param VersionsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoVersionsPostRequestBody(versionsPostRequestBody: Partial<VersionsPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "version": n => { versionsPostRequestBody.version = n.getObjectValue<CreateLayerVersionCommand>(createCreateLayerVersionCommandFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param VersionsPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeVersionsPostRequestBody(writer: SerializationWriter, versionsPostRequestBody: Partial<VersionsPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!versionsPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<CreateLayerVersionCommand>("version", versionsPostRequestBody.version, serializeCreateLayerVersionCommand);
    writer.writeAdditionalData(versionsPostRequestBody.additionalData);
}
export interface VersionsPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The version property
     */
    version?: CreateLayerVersionCommand | null;
}
/**
 * Builds and executes requests for operations under /ifcx-api/layers/{layerId}/versions
 */
export interface VersionsRequestBuilder extends BaseRequestBuilder<VersionsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.ifcxApi.layers.item.versions.item collection
     * @param versionId Unique identifier of the item
     * @returns {WithVersionItemRequestBuilder}
     */
     byVersionId(versionId: string) : WithVersionItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(body: VersionsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: VersionsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VersionsRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers/{layerId}/versions";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VersionsRequestBuilderNavigationMetadata: Record<Exclude<keyof VersionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byVersionId: {
        requestsMetadata: WithVersionItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithVersionItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["versionId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const VersionsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: VersionsRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeVersionsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
