/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LayersRequestBuilderNavigationMetadata, LayersRequestBuilderRequestsMetadata, type LayersRequestBuilder } from './layers/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api
 */
export interface IfcxApiRequestBuilder extends BaseRequestBuilder<IfcxApiRequestBuilder> {
    /**
     * The layers property
     */
    get layers(): LayersRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const IfcxApiRequestBuilderUriTemplate = "{+baseurl}/ifcx-api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IfcxApiRequestBuilderNavigationMetadata: Record<Exclude<keyof IfcxApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    layers: {
        requestsMetadata: LayersRequestBuilderRequestsMetadata,
        navigationMetadata: LayersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
