// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateLayerVersionResponseState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "OUT_OF_DATE")]
        #pragma warning disable CS1591
        OUT_OF_DATE,
        #pragma warning restore CS1591
    }
}
