// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum IfcxFileDownloadType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "just_this_version")]
        #pragma warning disable CS1591
        Just_this_version,
        #pragma warning restore CS1591
        [EnumMember(Value = "whole_layer_history_intact")]
        #pragma warning disable CS1591
        Whole_layer_history_intact,
        #pragma warning restore CS1591
        [EnumMember(Value = "whole_layer_history_condensed")]
        #pragma warning disable CS1591
        Whole_layer_history_condensed,
        #pragma warning restore CS1591
        [EnumMember(Value = "whole_layer_and_imports_history_condensed")]
        #pragma warning disable CS1591
        Whole_layer_and_imports_history_condensed,
        #pragma warning restore CS1591
    }
}
