// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LayerVersion : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The layerId property</summary>
        public Guid? LayerId { get; set; }
        /// <summary>The previousVersionId property</summary>
        public Guid? PreviousVersionId { get; set; }
        /// <summary>The provenance property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiSdk.Models.IfcxProvenanceData? Provenance { get; set; }
#nullable restore
#else
        public global::ApiSdk.Models.IfcxProvenanceData Provenance { get; set; }
#endif
        /// <summary>The versionId property</summary>
        public Guid? VersionId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Models.LayerVersion"/> and sets the default values.
        /// </summary>
        public LayerVersion()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Models.LayerVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.Models.LayerVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.Models.LayerVersion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "layerId", n => { LayerId = n.GetGuidValue(); } },
                { "previousVersionId", n => { PreviousVersionId = n.GetGuidValue(); } },
                { "provenance", n => { Provenance = n.GetObjectValue<global::ApiSdk.Models.IfcxProvenanceData>(global::ApiSdk.Models.IfcxProvenanceData.CreateFromDiscriminatorValue); } },
                { "versionId", n => { VersionId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("layerId", LayerId);
            writer.WriteGuidValue("previousVersionId", PreviousVersionId);
            writer.WriteObjectValue<global::ApiSdk.Models.IfcxProvenanceData>("provenance", Provenance);
            writer.WriteGuidValue("versionId", VersionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
