#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/IfcxApi.Server/ && \
    dotnet build src/IfcxApi.Server/ && \
    echo "Now, run the following to start the project: dotnet run -p src/IfcxApi.Server/IfcxApi.Server.csproj --launch-profile web"
