/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLayerVersionFromDiscriminatorValue, type LayerVersion } from '../../../../../models/index.js';
// @ts-ignore
import { DownloadIfcxRequestBuilderRequestsMetadata, type DownloadIfcxRequestBuilder } from './downloadIfcx/index.js';
// @ts-ignore
import { QueryRequestBuilderRequestsMetadata, type QueryRequestBuilder } from './query/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/layers/{layerId}/versions/{versionId}
 */
export interface WithVersionItemRequestBuilder extends BaseRequestBuilder<WithVersionItemRequestBuilder> {
    /**
     * The downloadIfcx property
     */
    get downloadIfcx(): DownloadIfcxRequestBuilder;
    /**
     * The query property
     */
    get query(): QueryRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LayerVersion>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LayerVersion | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithVersionItemRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers/{layerId}/versions/{versionId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithVersionItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithVersionItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    downloadIfcx: {
        requestsMetadata: DownloadIfcxRequestBuilderRequestsMetadata,
    },
    query: {
        requestsMetadata: QueryRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithVersionItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithVersionItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createLayerVersionFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
