/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLayerDetailsFromDiscriminatorValue, type LayerDetails } from '../../../models/index.js';
// @ts-ignore
import { type UploadIfcxBlobUrlRequestBuilder, UploadIfcxBlobUrlRequestBuilderRequestsMetadata } from './uploadIfcxBlobUrl/index.js';
// @ts-ignore
import { type VersionsRequestBuilder, VersionsRequestBuilderNavigationMetadata, VersionsRequestBuilderRequestsMetadata } from './versions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/layers/{layerId}
 */
export interface WithLayerItemRequestBuilder extends BaseRequestBuilder<WithLayerItemRequestBuilder> {
    /**
     * The uploadIfcxBlobUrl property
     */
    get uploadIfcxBlobUrl(): UploadIfcxBlobUrlRequestBuilder;
    /**
     * The versions property
     */
    get versions(): VersionsRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LayerDetails>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LayerDetails | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithLayerItemRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers/{layerId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithLayerItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithLayerItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    uploadIfcxBlobUrl: {
        requestsMetadata: UploadIfcxBlobUrlRequestBuilderRequestsMetadata,
    },
    versions: {
        requestsMetadata: VersionsRequestBuilderRequestsMetadata,
        navigationMetadata: VersionsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithLayerItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithLayerItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: WithLayerItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createLayerDetailsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
