/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLayerDetailsFromDiscriminatorValue, createUpdateLayerCommandFromDiscriminatorValue, serializeUpdateLayerCommand, type LayerDetails, type UpdateLayerCommand } from '../../../models/index.js';
// @ts-ignore
import { HistoryRequestBuilderRequestsMetadata, type HistoryRequestBuilder } from './history/index.js';
// @ts-ignore
import { type UploadIfcxBlobUrlRequestBuilder, UploadIfcxBlobUrlRequestBuilderRequestsMetadata } from './uploadIfcxBlobUrl/index.js';
// @ts-ignore
import { type VersionsRequestBuilder, VersionsRequestBuilderNavigationMetadata, VersionsRequestBuilderRequestsMetadata } from './versions/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithLayerPutRequestBody}
 */
// @ts-ignore
export function createWithLayerPutRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithLayerPutRequestBody;
}
/**
 * The deserialization information for the current model
 * @param WithLayerPutRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithLayerPutRequestBody(withLayerPutRequestBody: Partial<WithLayerPutRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "version": n => { withLayerPutRequestBody.version = n.getObjectValue<UpdateLayerCommand>(createUpdateLayerCommandFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithLayerPutRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithLayerPutRequestBody(writer: SerializationWriter, withLayerPutRequestBody: Partial<WithLayerPutRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withLayerPutRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<UpdateLayerCommand>("version", withLayerPutRequestBody.version, serializeUpdateLayerCommand);
    writer.writeAdditionalData(withLayerPutRequestBody.additionalData);
}
/**
 * Builds and executes requests for operations under /ifcx-api/layers/{layerId}
 */
export interface WithLayerItemRequestBuilder extends BaseRequestBuilder<WithLayerItemRequestBuilder> {
    /**
     * The history property
     */
    get history(): HistoryRequestBuilder;
    /**
     * The uploadIfcxBlobUrl property
     */
    get uploadIfcxBlobUrl(): UploadIfcxBlobUrlRequestBuilder;
    /**
     * The versions property
     */
    get versions(): VersionsRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LayerDetails>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LayerDetails | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     put(body: WithLayerPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: WithLayerPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface WithLayerPutRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The version property
     */
    version?: UpdateLayerCommand | null;
}
/**
 * Uri template for the request builder.
 */
export const WithLayerItemRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers/{layerId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithLayerItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithLayerItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    history: {
        requestsMetadata: HistoryRequestBuilderRequestsMetadata,
    },
    uploadIfcxBlobUrl: {
        requestsMetadata: UploadIfcxBlobUrlRequestBuilderRequestsMetadata,
    },
    versions: {
        requestsMetadata: VersionsRequestBuilderRequestsMetadata,
        navigationMetadata: VersionsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithLayerItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithLayerItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: WithLayerItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createLayerDetailsFromDiscriminatorValue,
    },
    put: {
        uriTemplate: WithLayerItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWithLayerPutRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
