/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithBlobItemRequestBuilder, WithBlobItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/upload
 */
export interface UploadRequestBuilder extends BaseRequestBuilder<UploadRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.ifcxApi.upload.item collection
     * @param blobId Unique identifier of the item
     * @returns {WithBlobItemRequestBuilder}
     */
     byBlobId(blobId: Guid) : WithBlobItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const UploadRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/upload";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UploadRequestBuilderNavigationMetadata: Record<Exclude<keyof UploadRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBlobId: {
        requestsMetadata: WithBlobItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["blobId"],
    },
};
/* tslint:enable */
/* eslint-enable */
