// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.IfcxApi.Download;
using ApiSdk.IfcxApi.Layers;
using ApiSdk.IfcxApi.Upload;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk.IfcxApi
{
    /// <summary>
    /// Builds and executes requests for operations under \ifcx-api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IfcxApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The download property</summary>
        public global::ApiSdk.IfcxApi.Download.DownloadRequestBuilder Download
        {
            get => new global::ApiSdk.IfcxApi.Download.DownloadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The layers property</summary>
        public global::ApiSdk.IfcxApi.Layers.LayersRequestBuilder Layers
        {
            get => new global::ApiSdk.IfcxApi.Layers.LayersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload property</summary>
        public global::ApiSdk.IfcxApi.Upload.UploadRequestBuilder Upload
        {
            get => new global::ApiSdk.IfcxApi.Upload.UploadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.IfcxApi.IfcxApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IfcxApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ifcx-api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.IfcxApi.IfcxApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IfcxApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ifcx-api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
