/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/download/{blobId}
 */
export interface WithBlobItemRequestBuilder extends BaseRequestBuilder<WithBlobItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     put(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithBlobItemRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/download/{blobId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithBlobItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: WithBlobItemRequestBuilderUriTemplate,
        responseBodyContentType: "*/*",
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
