/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithBlobItemRequestBuilder, WithBlobItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/download
 */
export interface DownloadRequestBuilder extends BaseRequestBuilder<DownloadRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.ifcxApi.download.item collection
     * @param blobId Unique identifier of the item
     * @returns {WithBlobItemRequestBuilder}
     */
     byBlobId(blobId: Guid) : WithBlobItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DownloadRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/download";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DownloadRequestBuilderNavigationMetadata: Record<Exclude<keyof DownloadRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBlobId: {
        requestsMetadata: WithBlobItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["blobId"],
    },
};
/* tslint:enable */
/* eslint-enable */
