/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface BlobResponse extends AdditionalDataHolder, Parsable {
    /**
     * The blobId property
     */
    blobId?: Guid | null;
    /**
     * The putURL property
     */
    putURL?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BlobResponse}
 */
// @ts-ignore
export function createBlobResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBlobResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateLayerCommand}
 */
// @ts-ignore
export function createCreateLayerCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateLayerCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateLayerVersionCommand}
 */
// @ts-ignore
export function createCreateLayerVersionCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateLayerVersionCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateLayerVersionResponse}
 */
// @ts-ignore
export function createCreateLayerVersionResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateLayerVersionResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {IfcxProvenanceData}
 */
// @ts-ignore
export function createIfcxProvenanceDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoIfcxProvenanceData;
}
export interface CreateLayerCommand extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerDetails}
 */
// @ts-ignore
export function createLayerDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerStatus}
 */
// @ts-ignore
export function createLayerStatusFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerStatus;
}
export interface CreateLayerVersionCommand extends AdditionalDataHolder, Parsable {
    /**
     * The blobId property
     */
    blobId?: Guid | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The previousLayerVersionId property
     */
    previousLayerVersionId?: Guid | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerVersion}
 */
// @ts-ignore
export function createLayerVersionFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerVersion;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerVersionIfcxFile}
 */
// @ts-ignore
export function createLayerVersionIfcxFileFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerVersionIfcxFile;
}
export interface CreateLayerVersionResponse extends AdditionalDataHolder, Parsable {
    /**
     * The state property
     */
    state?: CreateLayerVersionResponseState | null;
}
export type CreateLayerVersionResponseState = (typeof CreateLayerVersionResponseStateObject)[keyof typeof CreateLayerVersionResponseStateObject];
/**
 * The deserialization information for the current model
 * @param BlobResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBlobResponse(blobResponse: Partial<BlobResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "blobId": n => { blobResponse.blobId = n.getGuidValue(); },
        "putURL": n => { blobResponse.putURL = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateLayerCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateLayerCommand(createLayerCommand: Partial<CreateLayerCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { createLayerCommand.id = n.getGuidValue(); },
        "name": n => { createLayerCommand.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateLayerVersionCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateLayerVersionCommand(createLayerVersionCommand: Partial<CreateLayerVersionCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "blobId": n => { createLayerVersionCommand.blobId = n.getGuidValue(); },
        "id": n => { createLayerVersionCommand.id = n.getGuidValue(); },
        "previousLayerVersionId": n => { createLayerVersionCommand.previousLayerVersionId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateLayerVersionResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateLayerVersionResponse(createLayerVersionResponse: Partial<CreateLayerVersionResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "state": n => { createLayerVersionResponse.state = n.getEnumValue<CreateLayerVersionResponseState>(CreateLayerVersionResponseStateObject); },
    }
}
/**
 * The deserialization information for the current model
 * @param IfcxProvenanceData The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoIfcxProvenanceData(ifcxProvenanceData: Partial<IfcxProvenanceData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "application": n => { ifcxProvenanceData.application = n.getStringValue(); },
        "author": n => { ifcxProvenanceData.author = n.getStringValue(); },
        "timestamp": n => { ifcxProvenanceData.timestamp = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerDetails(layerDetails: Partial<LayerDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "history": n => { layerDetails.history = n.getCollectionOfObjectValues<LayerVersion>(createLayerVersionFromDiscriminatorValue); },
        "id": n => { layerDetails.id = n.getGuidValue(); },
        "name": n => { layerDetails.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerStatus The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerStatus(layerStatus: Partial<LayerStatus> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { layerStatus.id = n.getGuidValue(); },
        "latestVersion": n => { layerStatus.latestVersion = n.getGuidValue(); },
        "name": n => { layerStatus.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerVersion The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerVersion(layerVersion: Partial<LayerVersion> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "layerId": n => { layerVersion.layerId = n.getGuidValue(); },
        "previousVersionId": n => { layerVersion.previousVersionId = n.getGuidValue(); },
        "provenance": n => { layerVersion.provenance = n.getObjectValue<IfcxProvenanceData>(createIfcxProvenanceDataFromDiscriminatorValue); },
        "versionId": n => { layerVersion.versionId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerVersionIfcxFile The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerVersionIfcxFile(layerVersionIfcxFile: Partial<LayerVersionIfcxFile> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "blobUrl": n => { layerVersionIfcxFile.blobUrl = n.getStringValue(); },
    }
}
export type IfcxFileDownloadType = (typeof IfcxFileDownloadTypeObject)[keyof typeof IfcxFileDownloadTypeObject];
export interface IfcxProvenanceData extends AdditionalDataHolder, Parsable {
    /**
     * The application property
     */
    application?: string | null;
    /**
     * The author property
     */
    author?: string | null;
    /**
     * The timestamp property
     */
    timestamp?: string | null;
}
export interface LayerDetails extends AdditionalDataHolder, Parsable {
    /**
     * The history property
     */
    history?: LayerVersion[] | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface LayerStatus extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The latestVersion property
     */
    latestVersion?: Guid | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface LayerVersion extends AdditionalDataHolder, Parsable {
    /**
     * The layerId property
     */
    layerId?: Guid | null;
    /**
     * The previousVersionId property
     */
    previousVersionId?: Guid | null;
    /**
     * The provenance property
     */
    provenance?: IfcxProvenanceData | null;
    /**
     * The versionId property
     */
    versionId?: Guid | null;
}
export interface LayerVersionIfcxFile extends AdditionalDataHolder, Parsable {
    /**
     * The blobUrl property
     */
    blobUrl?: string | null;
}
/**
 * Serializes information the current object
 * @param BlobResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBlobResponse(writer: SerializationWriter, blobResponse: Partial<BlobResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!blobResponse || isSerializingDerivedType) { return; }
    writer.writeGuidValue("blobId", blobResponse.blobId);
    writer.writeStringValue("putURL", blobResponse.putURL);
    writer.writeAdditionalData(blobResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateLayerCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateLayerCommand(writer: SerializationWriter, createLayerCommand: Partial<CreateLayerCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createLayerCommand || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", createLayerCommand.id);
    writer.writeStringValue("name", createLayerCommand.name);
    writer.writeAdditionalData(createLayerCommand.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateLayerVersionCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateLayerVersionCommand(writer: SerializationWriter, createLayerVersionCommand: Partial<CreateLayerVersionCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createLayerVersionCommand || isSerializingDerivedType) { return; }
    writer.writeGuidValue("blobId", createLayerVersionCommand.blobId);
    writer.writeGuidValue("id", createLayerVersionCommand.id);
    writer.writeGuidValue("previousLayerVersionId", createLayerVersionCommand.previousLayerVersionId);
    writer.writeAdditionalData(createLayerVersionCommand.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateLayerVersionResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateLayerVersionResponse(writer: SerializationWriter, createLayerVersionResponse: Partial<CreateLayerVersionResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createLayerVersionResponse || isSerializingDerivedType) { return; }
    writer.writeEnumValue<CreateLayerVersionResponseState>("state", createLayerVersionResponse.state);
    writer.writeAdditionalData(createLayerVersionResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param IfcxProvenanceData The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeIfcxProvenanceData(writer: SerializationWriter, ifcxProvenanceData: Partial<IfcxProvenanceData> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!ifcxProvenanceData || isSerializingDerivedType) { return; }
    writer.writeStringValue("application", ifcxProvenanceData.application);
    writer.writeStringValue("author", ifcxProvenanceData.author);
    writer.writeStringValue("timestamp", ifcxProvenanceData.timestamp);
    writer.writeAdditionalData(ifcxProvenanceData.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerDetails(writer: SerializationWriter, layerDetails: Partial<LayerDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerDetails || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<LayerVersion>("history", layerDetails.history, serializeLayerVersion);
    writer.writeGuidValue("id", layerDetails.id);
    writer.writeStringValue("name", layerDetails.name);
    writer.writeAdditionalData(layerDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerStatus The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerStatus(writer: SerializationWriter, layerStatus: Partial<LayerStatus> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerStatus || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", layerStatus.id);
    writer.writeGuidValue("latestVersion", layerStatus.latestVersion);
    writer.writeStringValue("name", layerStatus.name);
    writer.writeAdditionalData(layerStatus.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerVersion The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerVersion(writer: SerializationWriter, layerVersion: Partial<LayerVersion> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerVersion || isSerializingDerivedType) { return; }
    writer.writeGuidValue("layerId", layerVersion.layerId);
    writer.writeGuidValue("previousVersionId", layerVersion.previousVersionId);
    writer.writeObjectValue<IfcxProvenanceData>("provenance", layerVersion.provenance, serializeIfcxProvenanceData);
    writer.writeGuidValue("versionId", layerVersion.versionId);
    writer.writeAdditionalData(layerVersion.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerVersionIfcxFile The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerVersionIfcxFile(writer: SerializationWriter, layerVersionIfcxFile: Partial<LayerVersionIfcxFile> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerVersionIfcxFile || isSerializingDerivedType) { return; }
    writer.writeStringValue("blobUrl", layerVersionIfcxFile.blobUrl);
    writer.writeAdditionalData(layerVersionIfcxFile.additionalData);
}
export const CreateLayerVersionResponseStateObject = {
    OK: "OK",
    OUT_OF_DATE: "OUT_OF_DATE",
} as const;
export const IfcxFileDownloadTypeObject = {
    Just_this_version: "just_this_version",
    Whole_layer_history_intact: "whole_layer_history_intact",
    Whole_layer_history_condensed: "whole_layer_history_condensed",
    Whole_layer_and_imports_history_condensed: "whole_layer_and_imports_history_condensed",
} as const;
/* tslint:enable */
/* eslint-enable */
