/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateLayerCommand}
 */
// @ts-ignore
export function createCreateLayerCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateLayerCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateLayerVersionCommand}
 */
// @ts-ignore
export function createCreateLayerVersionCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateLayerVersionCommand;
}
export interface CreateLayerCommand extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerDetails}
 */
// @ts-ignore
export function createLayerDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerHistory}
 */
// @ts-ignore
export function createLayerHistoryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerHistory;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerStatus}
 */
// @ts-ignore
export function createLayerStatusFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerStatus;
}
export interface CreateLayerVersionCommand extends AdditionalDataHolder, Parsable {
    /**
     * The blobId property
     */
    blobId?: string | null;
    /**
     * The layerId property
     */
    layerId?: string | null;
    /**
     * The previousLayerVersionId property
     */
    previousLayerVersionId?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerVersion}
 */
// @ts-ignore
export function createLayerVersionFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerVersion;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayerVersionIfcxFile}
 */
// @ts-ignore
export function createLayerVersionIfcxFileFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayerVersionIfcxFile;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateLayerCommand}
 */
// @ts-ignore
export function createUpdateLayerCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateLayerCommand;
}
/**
 * The deserialization information for the current model
 * @param CreateLayerCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateLayerCommand(createLayerCommand: Partial<CreateLayerCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { createLayerCommand.id = n.getStringValue(); },
        "name": n => { createLayerCommand.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateLayerVersionCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateLayerVersionCommand(createLayerVersionCommand: Partial<CreateLayerVersionCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "blobId": n => { createLayerVersionCommand.blobId = n.getStringValue(); },
        "layerId": n => { createLayerVersionCommand.layerId = n.getStringValue(); },
        "previousLayerVersionId": n => { createLayerVersionCommand.previousLayerVersionId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerDetails(layerDetails: Partial<LayerDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { layerDetails.id = n.getStringValue(); },
        "latestVersion": n => { layerDetails.latestVersion = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerHistory The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerHistory(layerHistory: Partial<LayerHistory> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { layerHistory.id = n.getStringValue(); },
        "versions": n => { layerHistory.versions = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerStatus The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerStatus(layerStatus: Partial<LayerStatus> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { layerStatus.id = n.getStringValue(); },
        "latestVersion": n => { layerStatus.latestVersion = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerVersion The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerVersion(layerVersion: Partial<LayerVersion> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "layerId": n => { layerVersion.layerId = n.getStringValue(); },
        "previousVersionId": n => { layerVersion.previousVersionId = n.getStringValue(); },
        "versionId": n => { layerVersion.versionId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LayerVersionIfcxFile The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayerVersionIfcxFile(layerVersionIfcxFile: Partial<LayerVersionIfcxFile> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "blobUrl": n => { layerVersionIfcxFile.blobUrl = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateLayerCommand The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateLayerCommand(updateLayerCommand: Partial<UpdateLayerCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { updateLayerCommand.name = n.getStringValue(); },
    }
}
export type IfcxFileDownloadType = (typeof IfcxFileDownloadTypeObject)[keyof typeof IfcxFileDownloadTypeObject];
export interface LayerDetails extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The latestVersion property
     */
    latestVersion?: string | null;
}
export interface LayerHistory extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The versions property
     */
    versions?: string[] | null;
}
export interface LayerStatus extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The latestVersion property
     */
    latestVersion?: string | null;
}
export interface LayerVersion extends AdditionalDataHolder, Parsable {
    /**
     * The layerId property
     */
    layerId?: string | null;
    /**
     * The previousVersionId property
     */
    previousVersionId?: string | null;
    /**
     * The versionId property
     */
    versionId?: string | null;
}
export interface LayerVersionIfcxFile extends AdditionalDataHolder, Parsable {
    /**
     * The blobUrl property
     */
    blobUrl?: string | null;
}
/**
 * Serializes information the current object
 * @param CreateLayerCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateLayerCommand(writer: SerializationWriter, createLayerCommand: Partial<CreateLayerCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createLayerCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("id", createLayerCommand.id);
    writer.writeStringValue("name", createLayerCommand.name);
    writer.writeAdditionalData(createLayerCommand.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateLayerVersionCommand The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateLayerVersionCommand(writer: SerializationWriter, createLayerVersionCommand: Partial<CreateLayerVersionCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createLayerVersionCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("blobId", createLayerVersionCommand.blobId);
    writer.writeStringValue("layerId", createLayerVersionCommand.layerId);
    writer.writeStringValue("previousLayerVersionId", createLayerVersionCommand.previousLayerVersionId);
    writer.writeAdditionalData(createLayerVersionCommand.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerDetails(writer: SerializationWriter, layerDetails: Partial<LayerDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("id", layerDetails.id);
    writer.writeStringValue("latestVersion", layerDetails.latestVersion);
    writer.writeAdditionalData(layerDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerHistory The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerHistory(writer: SerializationWriter, layerHistory: Partial<LayerHistory> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerHistory || isSerializingDerivedType) { return; }
    writer.writeStringValue("id", layerHistory.id);
    writer.writeCollectionOfPrimitiveValues<string>("versions", layerHistory.versions);
    writer.writeAdditionalData(layerHistory.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerStatus The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerStatus(writer: SerializationWriter, layerStatus: Partial<LayerStatus> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerStatus || isSerializingDerivedType) { return; }
    writer.writeStringValue("id", layerStatus.id);
    writer.writeStringValue("latestVersion", layerStatus.latestVersion);
    writer.writeAdditionalData(layerStatus.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerVersion The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerVersion(writer: SerializationWriter, layerVersion: Partial<LayerVersion> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerVersion || isSerializingDerivedType) { return; }
    writer.writeStringValue("layerId", layerVersion.layerId);
    writer.writeStringValue("previousVersionId", layerVersion.previousVersionId);
    writer.writeStringValue("versionId", layerVersion.versionId);
    writer.writeAdditionalData(layerVersion.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayerVersionIfcxFile The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayerVersionIfcxFile(writer: SerializationWriter, layerVersionIfcxFile: Partial<LayerVersionIfcxFile> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layerVersionIfcxFile || isSerializingDerivedType) { return; }
    writer.writeStringValue("blobUrl", layerVersionIfcxFile.blobUrl);
    writer.writeAdditionalData(layerVersionIfcxFile.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateLayerCommand The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateLayerCommand(writer: SerializationWriter, updateLayerCommand: Partial<UpdateLayerCommand> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateLayerCommand || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", updateLayerCommand.name);
    writer.writeAdditionalData(updateLayerCommand.additionalData);
}
export interface UpdateLayerCommand extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
export const IfcxFileDownloadTypeObject = {
    Just_this_version: "just_this_version",
    Whole_layer_history_intact: "whole_layer_history_intact",
    Whole_layer_history_condensed: "whole_layer_history_condensed",
    Whole_layer_and_imports_history_condensed: "whole_layer_and_imports_history_condensed",
} as const;
/* tslint:enable */
/* eslint-enable */
