/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/layers/{layerId}/versions/{versionId}/query
 */
export interface QueryRequestBuilder extends BaseRequestBuilder<QueryRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<QueryRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<QueryRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface QueryRequestBuilderGetQueryParameters {
    expandChildren?: boolean;
    expandChildrenRecursive?: boolean;
    path?: string;
    provenance?: boolean;
}
/**
 * Uri template for the request builder.
 */
export const QueryRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers/{layerId}/versions/{versionId}/query?expandChildren={expandChildren}&expandChildrenRecursive={expandChildrenRecursive}&path={path}&provenance={provenance}";
/**
 * Metadata for all the requests in the request builder.
 */
export const QueryRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QueryRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
