/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Text.Json;
using IfcxApi.Server.Attributes;
using IfcxApi.Server.Models;

namespace IfcxApi.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class DefaultApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="blobId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPut]
        [Route("/ifcx-api/download/{blobId}")]
        [ValidateModelState]
        [SwaggerOperation("Download")]
        [SwaggerResponse(statusCode: 200, type: typeof(System.IO.Stream), description: "The request has succeeded.")]
        public abstract IActionResult Download([FromRoute (Name = "blobId")][Required]Guid blobId);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpDelete]
        [Route("/ifcx-api/layers/{layerId}")]
        [ValidateModelState]
        [SwaggerOperation("LayerRoutesDeleteLayer")]
        public abstract IActionResult LayerRoutesDeleteLayer([FromRoute (Name = "layerId")][Required]Guid layerId);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers/{layerId}")]
        [ValidateModelState]
        [SwaggerOperation("LayerRoutesGetLayer")]
        [SwaggerResponse(statusCode: 200, type: typeof(LayerDetails), description: "The request has succeeded.")]
        public abstract IActionResult LayerRoutesGetLayer([FromRoute (Name = "layerId")][Required]Guid layerId);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPost]
        [Route("/ifcx-api/layers/{layerId}/upload-ifcx-blob-url")]
        [ValidateModelState]
        [SwaggerOperation("LayerRoutesUploadIfcxBlobUrl")]
        [SwaggerResponse(statusCode: 200, type: typeof(BlobResponse), description: "The request has succeeded.")]
        public abstract IActionResult LayerRoutesUploadIfcxBlobUrl([FromRoute (Name = "layerId")][Required]Guid layerId);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="versionId"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers/{layerId}/versions/{versionId}")]
        [ValidateModelState]
        [SwaggerOperation("LayerVersionRoutesGetLayerVersion")]
        [SwaggerResponse(statusCode: 200, type: typeof(LayerVersion), description: "The request has succeeded.")]
        public abstract IActionResult LayerVersionRoutesGetLayerVersion([FromRoute (Name = "layerId")][Required]Guid layerId, [FromRoute (Name = "versionId")][Required]Guid versionId);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="versionId"></param>
        /// <param name="downloadType"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPut]
        [Route("/ifcx-api/layers/{layerId}/versions/{versionId}/download-ifcx")]
        [ValidateModelState]
        [SwaggerOperation("LayerVersionRoutesLayerIfcx")]
        [SwaggerResponse(statusCode: 200, type: typeof(LayerVersionIfcxFile), description: "The request has succeeded.")]
        public abstract IActionResult LayerVersionRoutesLayerIfcx([FromRoute (Name = "layerId")][Required]Guid layerId, [FromRoute (Name = "versionId")][Required]Guid versionId, [FromQuery (Name = "downloadType")][Required()]IfcxFileDownloadType downloadType);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="versionId"></param>
        /// <param name="path"></param>
        /// <param name="provenance"></param>
        /// <param name="expandChildren"></param>
        /// <param name="expandChildrenRecursive"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers/{layerId}/versions/{versionId}/query")]
        [ValidateModelState]
        [SwaggerOperation("LayerVersionRoutesQuery")]
        public abstract IActionResult LayerVersionRoutesQuery([FromRoute (Name = "layerId")][Required]Guid layerId, [FromRoute (Name = "versionId")][Required]Guid versionId, [FromQuery (Name = "path")][Required()]string path, [FromQuery (Name = "provenance")][Required()]bool provenance, [FromQuery (Name = "expandChildren")][Required()]bool expandChildren, [FromQuery (Name = "expandChildrenRecursive")][Required()]bool expandChildrenRecursive);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="createLayerCommand"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPost]
        [Route("/ifcx-api/layers")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("LayersCreateLayer")]
        public abstract IActionResult LayersCreateLayer([FromBody]CreateLayerCommand createLayerCommand);

        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">The request has succeeded.</response>
        [HttpGet]
        [Route("/ifcx-api/layers")]
        [ValidateModelState]
        [SwaggerOperation("LayersLayers")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<LayerStatus>), description: "The request has succeeded.")]
        public abstract IActionResult LayersLayers();

        /// <summary>
        /// 
        /// </summary>
        /// <param name="blobId"></param>
        /// <param name="body"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPut]
        [Route("/ifcx-api/upload/{blobId}")]
        [ValidateModelState]
        [SwaggerOperation("Upload")]
        public abstract IActionResult Upload([FromRoute (Name = "blobId")][Required]Guid blobId, [FromBody]System.IO.Stream body);

        /// <summary>
        /// 
        /// </summary>
        /// <param name="layerId"></param>
        /// <param name="createLayerVersionCommand"></param>
        /// <response code="200">The request has succeeded.</response>
        [HttpPost]
        [Route("/ifcx-api/layers/{layerId}/versions")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("VersionsRoutesCreateLayerVersion")]
        [SwaggerResponse(statusCode: 200, type: typeof(CreateLayerVersionResponse), description: "The request has succeeded.")]
        public abstract IActionResult VersionsRoutesCreateLayerVersion([FromRoute (Name = "layerId")][Required]Guid layerId, [FromBody]CreateLayerVersionCommand createLayerVersionCommand);
    }
}
