@startuml
class 25503984-6605-43a1-8597-eae657ff5bea {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcWindow', 'uri': ' [...] fcWindow'}"
  # "customdata" : "{'originalStepInstance': "#459 [...] ED.,$,$)"}"
}

class 14adb22b-d474-48a2-8e8f-6d4c067c1953 {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcProject', 'uri':  [...] cProject'}"
  # "customdata" : "{'originalStepInstance': "#1=I [...] #26),#9)"}"
}

class ab143723-f7b1-5368-b106-55896e88d768 {
}

class e0834921-e095-40f0-8874-3c6bd1ec699e {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcSite', 'uri': 'ht [...] /IfcSite'}"
  # "customdata" : "{'originalStepInstance': "#30= [...] $,$,$,$)"}"
}

class e84dc79e-fe9d-4781-9f4b-54dd435cca91 {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcBuilding', 'uri': [...] Building'}"
  # "customdata" : "{'originalStepInstance': "#36= [...] $,$,$,$)"}"
}

class 44af358b-3160-4063-8a89-a868335ff3b5 {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcBuildingStorey',  [...] ngStorey'}"
  # "customdata" : "{'originalStepInstance': "#42= [...] $,$,$,$)"}"
}

class e3035b71-bd9f-4cdc-86fd-b56e2f4605b6 {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcSpace', 'uri': 'h [...] IfcSpace'}"
  ~ "usd::xformop" : "{'transform': [[1, 0, 0, 0], [ [...] 8, 0, 1]]}"
  # "customdata" : "{'originalStepInstance': "#149 [...] PACE.,$)"}"
}

class 93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcWall', 'uri': 'ht [...] /IfcWall'}"
  + "bsi::ifc::v5a::prop::isexternal" : "True"
  # "customdata" : "{'originalStepInstance': "#122 [...] 230,$,$)"}"
  # "nlsfb::class" : "{'code': '21.21', 'uri': 'http [...] ss/21.21'}"
}

class 2c2d549f-f9fe-4e22-8590-562fda81a690 {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcWindow', 'uri': ' [...] fcWindow'}"
  + "bsi::ifc::v5a::prop::isexternal" : "True"
  ~ "usd::xformop" : "{'transform': [[1, 0, 0, 0], [ [...] 0, 1, 1]]}"
  # "customdata" : "{'originalStepInstance': "#126 [...] $,$,$,$)"}"
}

class 592504dc-469a-44d6-9ae8-c801b591679b {
  + "bsi::ifc::v5a::schema::class" : "{'code': 'IfcWindow', 'uri': ' [...] fcWindow'}"
  + "bsi::ifc::v5a::prop::isexternal" : "True"
  ~ "usd::xformop" : "{'transform': [[1, 0, 0, 0], [ [...] 0, 1, 1]]}"
  # "customdata" : "{'originalStepInstance': "#140 [...] $,$,$,$)"}"
}

class d42f9890-1da9-400a-b313-11b5f27d0da0 {
  + "bsi::ifc::v5a::schema::spaceboundary" : "{'relatedelement': {'ref': '93 [...] f4605b6'}}"
}

class 4eb1fec0-7b91-4dd9-82ec-5e35003177ce {
  + "bsi::ifc::v5a::schema::spaceboundary" : "{'relatedelement': {'ref': '2c [...] f4605b6'}}"
}

class 3b674acb-4384-47de-9f72-0848c9cea8a1 {
  + "bsi::ifc::v5a::schema::spaceboundary" : "{'relatedelement': {'ref': '59 [...] f4605b6'}}"
}

class 0e586931-d0c7-520d-87a1-33977bfcc094 {
  + "bsi::ifc::v5a::schema::presentation::diffuseColor" : "[0.6, 0.7, 0.8]"
  + "bsi::ifc::v5a::schema::presentation::opacity" : "0.3"
}

class 7a187a90-3dcf-58cc-b3a6-51a9a407c55a {
  + "bsi::ifc::v5a::schema::presentation::diffuseColor" : "[0.8, 0.7, 0.6]"
  + "bsi::ifc::v5a::schema::presentation::opacity" : "1"
}

class 77e17b50-5b5a-54ff-8137-3ab205b6f5f8 {
  + "bsi::ifc::v5a::schema::presentation::diffuseColor" : "[0.6, 0.5, 0.4]"
  + "bsi::ifc::v5a::schema::presentation::opacity" : "0.8"
}

class 8fada721-cff8-590b-8d0b-9300b5fe8e18 {
  ~ "usd::usdgeom::mesh" : "{'faceVertexIndices': [3, 0, 1 [...] 96, 1.2]]}"
  ~ "usd::usdgeom::visibility" : "{'visibility': 'invisible'}"
}

class ea5dbe57-5159-5801-b2f9-6f0ca112829b {
  ~ "usd::usdgeom::mesh" : "{'faceVertexIndices': [3, 0, 1 [...] 02, 1.1]]}"
}

class 15289df1-5ae0-5fc9-8399-19de1fbb87a0 {
  ~ "usd::usdgeom::mesh" : "{'faceVertexIndices': [0, 1, 2 [...] 0, 0, 3]]}"
}

class 634f90c3-831e-5f29-a9b2-fa69b207821e {
  ~ "usd::usdgeom::mesh" : "{'faceVertexIndices': [3, 0, 1 [...]  0.1, 1]]}"
}

class 8407e490-ceaa-56e5-96df-2351d9110668 {
  ~ "usd::usdgeom::basiscurves" : "{'points': [[0, 0, 0], [10, 0, 0]]}"
}

class 9d1fce89-e179-5076-9a3b-1b40eef3524b {
  ~ "usd::usdgeom::basiscurves" : "{'points': [[0, 0, 0], [0, 0, 3]]}"
}

class 367f7f7d-b4c5-50fe-829a-6bbced170dd1 {
  ~ "usd::usdgeom::mesh" : "{'faceVertexIndices': [0, 1, 3 [...] 0, 0, 0]]}"
}

class 4e664ae2-7ff7-58d6-aa41-242e18e90a39 {
  ~ "usd::usdgeom::mesh" : "{'faceVertexIndices': [2, 0, 1 [...] e-08, 0]]}"
}

class 649111c2-c1f1-5708-ab70-a51981cdb354 {
  ~ "usd::usdgeom::mesh" : "{'faceVertexIndices': [3, 0, 1 [...] 08, 2.2]]}"
}

class bcefac1b-eb16-5817-9e81-2e35337651b2 {
  ~ "usd::usdgeom::mesh" : "{'faceVertexIndices': [1, 2, 3 [...] e-08, 1]]}"
}

class f079bafd-8733-48d8-85df-1c1656a17c1f {
  + "bsi::ifc::v5a::prop::volume" : "1.2959999568"
  + "bsi::ifc::v5a::prop::height" : "1.2"
  + "bsi::ifc::v5a::prop::volume" : "0.025999999592"
  + "bsi::ifc::v5a::prop::height" : "1.2"
  + "bsi::ifc::v5a::prop::volume" : "150.0"
  + "bsi::ifc::v5a::prop::height" : "3.0"
  + "bsi::ifc::v5a::prop::volume" : "2.783999976"
  + "bsi::ifc::v5a::prop::height" : "3.0"
  + "bsi::ifc::v5a::prop::volume" : "0.0"
  + "bsi::ifc::v5a::prop::height" : "0.0"
  + "bsi::ifc::v5a::prop::volume" : "0.0"
  + "bsi::ifc::v5a::prop::height" : "3.0"
  + "bsi::ifc::v5a::prop::volume" : "0.0"
  + "bsi::ifc::v5a::prop::height" : "1.2000000000000002"
  + "bsi::ifc::v5a::prop::volume" : "0.0"
  + "bsi::ifc::v5a::prop::height" : "1.2000000000000002"
}

"25503984-6605-43a1-8597-eae657ff5bea" --> "child:Void" "8fada721-cff8-590b-8d0b-9300b5fe8e18"
"25503984-6605-43a1-8597-eae657ff5bea" --> "child:Body" "ea5dbe57-5159-5801-b2f9-6f0ca112829b"
"14adb22b-d474-48a2-8e8f-6d4c067c1953" --> "child:My_Site" "e0834921-e095-40f0-8874-3c6bd1ec699e"
"ab143723-f7b1-5368-b106-55896e88d768" --o "inherits:i0" "14adb22b-d474-48a2-8e8f-6d4c067c1953"
"e0834921-e095-40f0-8874-3c6bd1ec699e" --> "child:My_Building" "e84dc79e-fe9d-4781-9f4b-54dd435cca91"
"e84dc79e-fe9d-4781-9f4b-54dd435cca91" --> "child:My_Storey" "44af358b-3160-4063-8a89-a868335ff3b5"
"44af358b-3160-4063-8a89-a868335ff3b5" --> "child:My_Space" "e3035b71-bd9f-4cdc-86fd-b56e2f4605b6"
"44af358b-3160-4063-8a89-a868335ff3b5" --> "child:Wall" "93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b"
"e3035b71-bd9f-4cdc-86fd-b56e2f4605b6" --> "child:Body" "15289df1-5ae0-5fc9-8399-19de1fbb87a0"
"e3035b71-bd9f-4cdc-86fd-b56e2f4605b6" --> "child:Boundary_Wall" "d42f9890-1da9-400a-b313-11b5f27d0da0"
"e3035b71-bd9f-4cdc-86fd-b56e2f4605b6" --> "child:Boundary_Window" "4eb1fec0-7b91-4dd9-82ec-5e35003177ce"
"e3035b71-bd9f-4cdc-86fd-b56e2f4605b6" --> "child:Boundary_Window_001" "3b674acb-4384-47de-9f72-0848c9cea8a1"
"93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b" --> "child:Body" "634f90c3-831e-5f29-a9b2-fa69b207821e"
"93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b" --> "child:Axis" "8407e490-ceaa-56e5-96df-2351d9110668"
"93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b" --> "child:Directrix" "9d1fce89-e179-5076-9a3b-1b40eef3524b"
"93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b" --> "child:Basis" "367f7f7d-b4c5-50fe-829a-6bbced170dd1"
"93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b" --> "child:Window" "2c2d549f-f9fe-4e22-8590-562fda81a690"
"93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b" --> "child:Window_001" "592504dc-469a-44d6-9ae8-c801b591679b"
"2c2d549f-f9fe-4e22-8590-562fda81a690" --o "inherits:i0" "25503984-6605-43a1-8597-eae657ff5bea"
"592504dc-469a-44d6-9ae8-c801b591679b" --o "inherits:i0" "25503984-6605-43a1-8597-eae657ff5bea"
"d42f9890-1da9-400a-b313-11b5f27d0da0" --> "child:Body" "4e664ae2-7ff7-58d6-aa41-242e18e90a39"
"4eb1fec0-7b91-4dd9-82ec-5e35003177ce" --> "child:Body" "649111c2-c1f1-5708-ab70-a51981cdb354"
"3b674acb-4384-47de-9f72-0848c9cea8a1" --> "child:Body" "bcefac1b-eb16-5817-9e81-2e35337651b2"
"e3035b71-bd9f-4cdc-86fd-b56e2f4605b6" --|> "madeOf" "0e586931-d0c7-520d-87a1-33977bfcc094"
"93791d5d-5beb-437b-b8ec-2f1f0ba4bf3b" --|> "madeOf" "7a187a90-3dcf-58cc-b3a6-51a9a407c55a"
"2c2d549f-f9fe-4e22-8590-562fda81a690" --|> "madeOf" "77e17b50-5b5a-54ff-8137-3ab205b6f5f8"
"592504dc-469a-44d6-9ae8-c801b591679b" --|> "madeOf" "77e17b50-5b5a-54ff-8137-3ab205b6f5f8"
@enduml
