// see docs/quantity-kinds.md for more info
enum QuantityKind
{
    PlaneAngle: "Plane angle";
    ThermodynamicTemperatue: "Thermodynamic temperature",
    ElectricCurrent: "Electric current",
    Time: "Time",
    Frequency: "Frequency",
    Mass: "Mass",
    Length: "Length",
    LinearVelocity: "Linear velocity",
    Force: "Force",
    Pressure: "Pressure",
    Area: "Area",
    Energy: "Energy",
    Power: "Power",
    Volume: "Volume",
}