// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var mycomponent = Mycomponent.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    // start insert
    public partial class Mycomponent
    {
    public static ifcx_sdk.IfcxIdentity<Mycomponent> Identity()
        {
            return new ifcx_sdk.IfcxIdentity<Mycomponent>
            {
                typeID = "examples::ifc5::mycomponent",
                originSchemaSrc = "{\r\n  \"$id\": \"https://example.com/person.schema.json\",\r\n  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",\r\n  \"x-ifc5-id\": \"examples::ifc5::mycomponent\",\r\n  \"title\": \"Person\",\r\n  \"type\": \"object\",\r\n  \"properties\": {\r\n    \"firstName\": {\r\n      \"type\": \"string\",\r\n      \"description\": \"The person's first name.\"\r\n    },\r\n    \"lastName\": {\r\n      \"type\": \"string\",\r\n      \"description\": \"The person's last name.\"\r\n    },\r\n    \"age\": {\r\n      \"description\": \"Age in years which must be equal to or greater than zero.\",\r\n      \"type\": \"integer\",\r\n      \"minimum\": 0\r\n    }\r\n  }\r\n}",
                fromJSONString = str => Mycomponent.FromJson(str),
                toJSONString = obj => Serialize.ToJson(obj)
            };
        }
    }

    // end insert

    public partial class Mycomponent
    {

        /// <summary>
        /// Age in years which must be equal to or greater than zero.
        /// </summary>
        [JsonProperty("age", NullValueHandling = NullValueHandling.Ignore)]
        public long? Age { get; set; }

        /// <summary>
        /// The person's first name.
        /// </summary>
        [JsonProperty("firstName", NullValueHandling = NullValueHandling.Ignore)]
        public string FirstName { get; set; }

        /// <summary>
        /// The person's last name.
        /// </summary>
        [JsonProperty("lastName", NullValueHandling = NullValueHandling.Ignore)]
        public string LastName { get; set; }
    }

    public partial class Mycomponent
    {
        public static Mycomponent FromJson(string json) => JsonConvert.DeserializeObject<Mycomponent>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Mycomponent self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}