/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using IfcxApi.Server.Converters;

namespace IfcxApi.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class LayerVersionIfcxFile : IEquatable<LayerVersionIfcxFile>
    {
        /// <summary>
        /// Gets or Sets BlobUrl
        /// </summary>
        [Required]
        [DataMember(Name="blobUrl", EmitDefaultValue=false)]
        public string BlobUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LayerVersionIfcxFile {\n");
            sb.Append("  BlobUrl: ").Append(BlobUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LayerVersionIfcxFile)obj);
        }

        /// <summary>
        /// Returns true if LayerVersionIfcxFile instances are equal
        /// </summary>
        /// <param name="other">Instance of LayerVersionIfcxFile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LayerVersionIfcxFile other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BlobUrl == other.BlobUrl ||
                    BlobUrl != null &&
                    BlobUrl.Equals(other.BlobUrl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BlobUrl != null)
                    hashCode = hashCode * 59 + BlobUrl.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LayerVersionIfcxFile left, LayerVersionIfcxFile right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LayerVersionIfcxFile left, LayerVersionIfcxFile right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
