/*
 * (title)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using IfcxApi.Server.Converters;

namespace IfcxApi.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class LayerVersion : IEquatable<LayerVersion>
    {
        /// <summary>
        /// Gets or Sets LayerId
        /// </summary>
        [Required]
        [DataMember(Name="layerId", EmitDefaultValue=false)]
        public string LayerId { get; set; }

        /// <summary>
        /// Gets or Sets VersionId
        /// </summary>
        [Required]
        [DataMember(Name="versionId", EmitDefaultValue=false)]
        public string VersionId { get; set; }

        /// <summary>
        /// Gets or Sets PreviousVersionId
        /// </summary>
        [Required]
        [DataMember(Name="previousVersionId", EmitDefaultValue=false)]
        public string PreviousVersionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LayerVersion {\n");
            sb.Append("  LayerId: ").Append(LayerId).Append("\n");
            sb.Append("  VersionId: ").Append(VersionId).Append("\n");
            sb.Append("  PreviousVersionId: ").Append(PreviousVersionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LayerVersion)obj);
        }

        /// <summary>
        /// Returns true if LayerVersion instances are equal
        /// </summary>
        /// <param name="other">Instance of LayerVersion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LayerVersion other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LayerId == other.LayerId ||
                    LayerId != null &&
                    LayerId.Equals(other.LayerId)
                ) && 
                (
                    VersionId == other.VersionId ||
                    VersionId != null &&
                    VersionId.Equals(other.VersionId)
                ) && 
                (
                    PreviousVersionId == other.PreviousVersionId ||
                    PreviousVersionId != null &&
                    PreviousVersionId.Equals(other.PreviousVersionId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (LayerId != null)
                    hashCode = hashCode * 59 + LayerId.GetHashCode();
                    if (VersionId != null)
                    hashCode = hashCode * 59 + VersionId.GetHashCode();
                    if (PreviousVersionId != null)
                    hashCode = hashCode * 59 + PreviousVersionId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LayerVersion left, LayerVersion right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LayerVersion left, LayerVersion right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
