/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreateLayerCommandFromDiscriminatorValue, createLayerStatusFromDiscriminatorValue, serializeCreateLayerCommand, type CreateLayerCommand, type LayerStatus } from '../../models/index.js';
// @ts-ignore
import { type WithLayerItemRequestBuilder, WithLayerItemRequestBuilderNavigationMetadata, WithLayerItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LayersPostRequestBody}
 */
// @ts-ignore
export function createLayersPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLayersPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param LayersPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLayersPostRequestBody(layersPostRequestBody: Partial<LayersPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "version": n => { layersPostRequestBody.version = n.getObjectValue<CreateLayerCommand>(createCreateLayerCommandFromDiscriminatorValue); },
    }
}
export interface LayersPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The version property
     */
    version?: CreateLayerCommand | null;
}
/**
 * Builds and executes requests for operations under /ifcx-api/layers
 */
export interface LayersRequestBuilder extends BaseRequestBuilder<LayersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.ifcxApi.layers.item collection
     * @param layerId Unique identifier of the item
     * @returns {WithLayerItemRequestBuilder}
     */
     byLayerId(layerId: string) : WithLayerItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LayerStatus[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LayerStatus[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(body: LayersPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: LayersPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LayersPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLayersPostRequestBody(writer: SerializationWriter, layersPostRequestBody: Partial<LayersPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!layersPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<CreateLayerCommand>("version", layersPostRequestBody.version, serializeCreateLayerCommand);
    writer.writeAdditionalData(layersPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const LayersRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LayersRequestBuilderNavigationMetadata: Record<Exclude<keyof LayersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLayerId: {
        requestsMetadata: WithLayerItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithLayerItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["layerId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LayersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LayersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createLayerStatusFromDiscriminatorValue,
    },
    post: {
        uriTemplate: LayersRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLayersPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
