/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createLayerStatusFromDiscriminatorValue, serializeCreateLayerCommand, type CreateLayerCommand, type LayerStatus } from '../../models/index.js';
// @ts-ignore
import { type WithLayerItemRequestBuilder, WithLayerItemRequestBuilderNavigationMetadata, WithLayerItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ifcx-api/layers
 */
export interface LayersRequestBuilder extends BaseRequestBuilder<LayersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.ifcxApi.layers.item collection
     * @param layerId Unique identifier of the item
     * @returns {WithLayerItemRequestBuilder}
     */
     byLayerId(layerId: Guid) : WithLayerItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LayerStatus[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<LayerStatus[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(body: CreateLayerCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateLayerCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LayersRequestBuilderUriTemplate = "{+baseurl}/ifcx-api/layers";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LayersRequestBuilderNavigationMetadata: Record<Exclude<keyof LayersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byLayerId: {
        requestsMetadata: WithLayerItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithLayerItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["layerId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LayersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LayersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createLayerStatusFromDiscriminatorValue,
    },
    post: {
        uriTemplate: LayersRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateLayerCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
