// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx
{
    /// <summary>
    /// Builds and executes requests for operations under \ifcx-api\layers\{layerId}\versions\{versionId}\download-ifcx
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadIfcxRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadIfcxRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ifcx-api/layers/{layerId}/versions/{versionId}/download-ifcx?downloadType={downloadType}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadIfcxRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ifcx-api/layers/{layerId}/versions/{versionId}/download-ifcx?downloadType={downloadType}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::ApiSdk.Models.LayerVersionIfcxFile"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Models.LayerVersionIfcxFile?> PutAsync(Action<RequestConfiguration<global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder.DownloadIfcxRequestBuilderPutQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Models.LayerVersionIfcxFile> PutAsync(Action<RequestConfiguration<global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder.DownloadIfcxRequestBuilderPutQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ApiSdk.Models.LayerVersionIfcxFile>(requestInfo, global::ApiSdk.Models.LayerVersionIfcxFile.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder.DownloadIfcxRequestBuilderPutQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder.DownloadIfcxRequestBuilderPutQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class DownloadIfcxRequestBuilderPutQueryParameters 
        #pragma warning restore CS1591
        {
            [Obsolete("This property is deprecated, use DownloadTypeAsIfcxFileDownloadType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("downloadType")]
            public string? DownloadType { get; set; }
#nullable restore
#else
            [QueryParameter("downloadType")]
            public string DownloadType { get; set; }
#endif
            [QueryParameter("downloadType")]
            public global::ApiSdk.Models.IfcxFileDownloadType? DownloadTypeAsIfcxFileDownloadType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DownloadIfcxRequestBuilderPutRequestConfiguration : RequestConfiguration<global::ApiSdk.IfcxApi.Layers.Item.Versions.Item.DownloadIfcx.DownloadIfcxRequestBuilder.DownloadIfcxRequestBuilderPutQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
